services:
  - type: web
    name: krypt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Krypt:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production